// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type DebtStatus string

const (
	DebtStatusPending  DebtStatus = "pending"
	DebtStatusPaid     DebtStatus = "paid"
	DebtStatusCanceled DebtStatus = "canceled"
)

func (e *DebtStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DebtStatus(s)
	case string:
		*e = DebtStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DebtStatus: %T", src)
	}
	return nil
}

type NullDebtStatus struct {
	DebtStatus DebtStatus
	Valid      bool // Valid is true if DebtStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDebtStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DebtStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DebtStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDebtStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DebtStatus), nil
}

type RiskLevel string

const (
	RiskLevelLow    RiskLevel = "low"
	RiskLevelMedium RiskLevel = "medium"
	RiskLevelHigh   RiskLevel = "high"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel
	Valid     bool // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type Debt struct {
	ID          int32
	LenderID    int32
	BorrowerID  int32
	Amount      int32
	CreatedAt   time.Time
	Description *string
	Status      DebtStatus
}

type DebtPayment struct {
	ID         int32
	DebtID     int32
	PayerID    int32
	ReceiverID int32
	Amount     int32
	Note       *string
	PaidAt     time.Time
	CreatedAt  time.Time
}

type Item struct {
	ID           int32
	Name         string
	TypeID       *int32
	TotalCost    int64
	Unit         int32
	Ticker       *string
	AffectProfit *bool
	RiskLevel    RiskLevel
	CreatedAt    time.Time
	PricePerUnit int64
	UserID       int32
}

type ItemType struct {
	ID   int32
	Name string
}

type User struct {
	ID        int32
	UserName  string
	Password  string
	CreatedAt time.Time
}
