// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createItemType = `-- name: CreateItemType :one
INSERT INTO item_types(name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateItemType(ctx context.Context, name string) (ItemType, error) {
	row := q.db.QueryRow(ctx, createItemType, name)
	var i ItemType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, name
FROM item_types
ORDER BY name
`

func (q *Queries) ListItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.Query(ctx, listItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
