// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Notification struct {
	ID        uuid.UUID
	UserID    string
	Channel   string
	Payload   []byte
	Status    string
	Attempts  int32
	CreatedAt time.Time
	SentAt    *time.Time
}

type User struct {
	ID        int32
	UserName  string
	Password  string
	CreatedAt time.Time
}
