// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Debt struct {
	ID         int32
	LenderID   int32
	BorrowerID int32
	Amount     int32
	CreatedAt  time.Time
}

type User struct {
	ID        int32
	UserName  string
	Password  string
	CreatedAt time.Time
}
