// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (lender, borrower, amount)
VALUES ($1, $2, $3)
RETURNING id, lender, borrower, amount, created_at
`

type CreateDebtParams struct {
	Lender   int32
	Borrower int32
	Amount   int32
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt, arg.Lender, arg.Borrower, arg.Amount)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.Lender,
		&i.Borrower,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
