// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (lender, borrower, amount)
VALUES ($1, $2, $3)
RETURNING id, lender, borrower, amount, created_at
`

type CreateDebtParams struct {
	Lender   int32
	Borrower int32
	Amount   int32
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt, arg.Lender, arg.Borrower, arg.Amount)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.Lender,
		&i.Borrower,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getDebtsByBorrowerID = `-- name: GetDebtsByBorrowerID :many
SELECT id, lender, borrower, amount, created_at FROM debts
WHERE borrower = $1
`

func (q *Queries) GetDebtsByBorrowerID(ctx context.Context, borrower int32) ([]Debt, error) {
	rows, err := q.db.Query(ctx, getDebtsByBorrowerID, borrower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.Lender,
			&i.Borrower,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
