// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const countDebtsByBorrowerID = `-- name: CountDebtsByBorrowerID :one
SELECT count(*)
FROM debts
WHERE borrower_id = $1
`

func (q *Queries) CountDebtsByBorrowerID(ctx context.Context, borrowerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countDebtsByBorrowerID, borrowerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (lender_id, borrower_id, amount)
VALUES ($1, $2, $3)
RETURNING id, lender_id, borrower_id, amount, created_at, description, status
`

type CreateDebtParams struct {
	LenderID   int32
	BorrowerID int32
	Amount     int32
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt, arg.LenderID, arg.BorrowerID, arg.Amount)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.LenderID,
		&i.BorrowerID,
		&i.Amount,
		&i.CreatedAt,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const createDebtPayment = `-- name: CreateDebtPayment :one
INSERT INTO debt_payments (payer_id, receiver_id, debt_id, amount, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, debt_id, payer_id, receiver_id, amount, note, paid_at, created_at
`

type CreateDebtPaymentParams struct {
	PayerID    int32
	ReceiverID int32
	DebtID     int32
	Amount     int32
	Note       *string
}

func (q *Queries) CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, createDebtPayment,
		arg.PayerID,
		arg.ReceiverID,
		arg.DebtID,
		arg.Amount,
		arg.Note,
	)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.PayerID,
		&i.ReceiverID,
		&i.Amount,
		&i.Note,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, lender_id, borrower_id, amount, created_at, description, status
FROM debts
WHERE id = $1
`

func (q *Queries) GetDebtByID(ctx context.Context, id int32) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.LenderID,
		&i.BorrowerID,
		&i.Amount,
		&i.CreatedAt,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const getDebtForUpdate = `-- name: GetDebtForUpdate :one
SELECT id, lender_id, borrower_id, amount, created_at, description, status
FROM debts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetDebtForUpdate(ctx context.Context, id int32) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtForUpdate, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.LenderID,
		&i.BorrowerID,
		&i.Amount,
		&i.CreatedAt,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const getDebtsByBorrowerID = `-- name: GetDebtsByBorrowerID :many
SELECT d.id,
       d.amount,
       COALESCE(SUM(p.amount), 0)::int AS paid_amount,
       d.amount - COALESCE(SUM(p.amount), 0)::int AS remaining_amount,
       d.created_at,
       d.status,
       d.lender_id,
       lu.user_name AS lender_username,
       d.borrower_id,
       bu.user_name AS borrower_username
FROM debts d
         LEFT JOIN debt_payments p ON p.debt_id = d.id
         JOIN users lu ON lu.id = d.lender_id
         JOIN users bu ON bu.id = d.borrower_id
WHERE d.borrower_id = $1
GROUP BY d.id, d.amount, d.created_at, d.status, d.lender_id, lu.user_name, d.borrower_id, bu.user_name
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type GetDebtsByBorrowerIDParams struct {
	BorrowerID int32
	Limit      int32
	Offset     int32
}

type GetDebtsByBorrowerIDRow struct {
	ID               int32
	Amount           int32
	PaidAmount       int32
	RemainingAmount  int32
	CreatedAt        time.Time
	Status           DebtStatus
	LenderID         int32
	LenderUsername   string
	BorrowerID       int32
	BorrowerUsername string
}

func (q *Queries) GetDebtsByBorrowerID(ctx context.Context, arg GetDebtsByBorrowerIDParams) ([]GetDebtsByBorrowerIDRow, error) {
	rows, err := q.db.Query(ctx, getDebtsByBorrowerID, arg.BorrowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtsByBorrowerIDRow
	for rows.Next() {
		var i GetDebtsByBorrowerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.PaidAmount,
			&i.RemainingAmount,
			&i.CreatedAt,
			&i.Status,
			&i.LenderID,
			&i.LenderUsername,
			&i.BorrowerID,
			&i.BorrowerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaidAmountByDebtID = `-- name: GetPaidAmountByDebtID :one
SELECT COALESCE(SUM(amount), 0)::int
FROM debt_payments
WHERE debt_id = $1
`

func (q *Queries) GetPaidAmountByDebtID(ctx context.Context, debtID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getPaidAmountByDebtID, debtID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const markDebtPaid = `-- name: MarkDebtPaid :exec
UPDATE debts
SET status = 'paid'
WHERE id = $1
`

func (q *Queries) MarkDebtPaid(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markDebtPaid, id)
	return err
}
